---
abstract: 'L<Net::Async::FastCGI> support for L<EntityModel::Web>'
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EntityModel-Web-NaFastCGI
requires:
  EntityModel::Web: 0.002
  Net::Async::FastCGI: 0.23
  Time::Checkpoint::Sequential: 0.002
  perl: 5.010
version: 0.002
